# encoding: UTF-8

# Doc#: 3712-02-00116 Out Of Box Audit Document Checklist
out_of_box_audit_document_checklist_general_fields = {
		:sampled_box_of => :integer,
		:po_no          => :string,
		:so_no_sto_no   => :string,
		:line_no        => :integer,
		:part_no        => :string,
		:ship_qty       => :integer,
}
out_of_box_audit_document_checklist_general_detail_fields = {
	:items => [
		"Barcode scan",
		"Packing method",
		"SO# / STO# / Line#",
		"SO# / STO# / Line#",
		"PO#",
		"PO#",
		"Delivery Number",
		"Device P/N"
		"Device P/N"
		"Ship to Address",
		"Ship to Address",
		"Number of Boxes",
		"Number of Boxes",
		"Number of Boxes",
		"Number of Boxes",
		"Quantity",
		"Quantity",
		"Quantity",
		"Quantity",
		"WO# & P/N",
		"WO# & P/N",
		"WO# & P/N",
		"Document attached out Box X of X",
		"Document attached out Box X of X",
		"Document attached out Box X of X",
	],
    :specs => [
	"Shipping label spec",
	"Packing spec",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"Invoice",
	"T-Card",
	"T-Card",
	"T-Card",
	"N/A",
	"N/A",
	"N/A",
	],
	:check_items => [
	"Use barcode scanner to read each barcodes on one label",
	"Packing method",
	"Packing list",
	"Shipping label",
	"Packing list",
	"Shipping label",
	"Packing list",
	"Packing list",
	"Shipping label",
	"Packing list",
	"Forwarder Label",
	"Packing list",
	"Shipping label",
	"Forwarder label",
	"Physical box qty",
	"Packing list",
	"Shipping label",
	"Physical product qty",
	"To partial outer box, the sum of the qty on the inner box label if match with the qty on the outer box label",
	"Weight label",
	"Shipping label",
	"Inner box label",
	"Invoice",
	"Packing list",
	"C of C",
	],
	:criterias => [
	"Barcode read out match with 'leading character + readable text'",
	"Packaging per instructions on BOM",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Match",
	"Out box X of X",
	"Out box X of X",
	"Out box X of X",
	],
	:check_list_result => :boolean,
}
generate_form 'QA', 'OutOfBoxAuditChecklist',
	(out_of_box_audit_document_checklist_general_fields.merge common_fields), out_of_box_audit_document_checklist_general_detail_fields

